# Generated by Django 2.2.3 on 2019-12-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='disp_aplicacao',
            field=models.CharField(choices=[('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A')], max_length=35, verbose_name='Disponibilidade da Camada da Aplicação'),
        ),
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='disp_balanceador',
            field=models.CharField(choices=[('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A')], max_length=35, verbose_name='Disponibilidade da Camada do Balanceador'),
        ),
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='disp_banco_dados',
            field=models.CharField(choices=[('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A')], max_length=35, verbose_name='Disponibilidade da Camada do Banco de Dados'),
        ),
    ]
