# Generated by Django 2.2.3 on 2019-10-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_impacto_potencial',
            name='impacto_Potencial',
            field=models.CharField(max_length=255, verbose_name='Consequência Causada Por Indisponibilidade Sistêmica'),
        ),
    ]
