# Generated by Django 2.2.3 on 2019-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_impacto_direto',
            name='impacto_Direto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serviço Impactado Diretamente'),
        ),
        migrations.AlterField(
            model_name='t_impacto_indireto',
            name='impacto_Indireto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serviço Impactado Indiretamente'),
        ),
    ]
