# Generated by Django 2.2.3 on 2019-10-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_Impacto_Dependencia',
            fields=[
                ('cod_Dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('dependencia', models.CharField(blank=True, max_length=128, verbose_name='Dependência')),
            ],
            options={
                'verbose_name': 'Impacto - Dependência',
                'verbose_name_plural': 'Impacto - Dependências',
            },
        ),
        migrations.CreateModel(
            name='t_Impacto_Fronteira',
            fields=[
                ('cod_Fronteira', models.AutoField(primary_key=True, serialize=False)),
                ('fronteira', models.CharField(blank=True, max_length=128, verbose_name='Fronteira')),
            ],
            options={
                'verbose_name': 'Impacto - Fronteira',
                'verbose_name_plural': 'Impacto - Fronteiras',
            },
        ),
        migrations.CreateModel(
            name='t_Impacto_Potencial',
            fields=[
                ('cod_Impacto_Potencial', models.AutoField(primary_key=True, serialize=False)),
                ('impacto_Potencial', models.CharField(max_length=255, verbose_name='Impacto Potencial')),
            ],
            options={
                'verbose_name': 'Impacto Potencial',
                'verbose_name_plural': 'Impactos Potenciais',
            },
        ),
        migrations.RemoveField(
            model_name='t_impacto_fronteiras',
            name='cod_impacto',
        ),
        migrations.RemoveField(
            model_name='t_impacto_potenciais',
            name='cod_Impacto',
        ),
        migrations.RemoveField(
            model_name='t_sistema_janelas',
            name='cod_Sistema',
        ),
        migrations.RemoveField(
            model_name='t_sistema_servico',
            name='cod_Sistema',
        ),
        migrations.AddField(
            model_name='t_sistema',
            name='janelas_Criticas',
            field=models.ManyToManyField(to='systems.t_Sistema_Janelas', verbose_name='Janelas Críticas'),
        ),
        migrations.AddField(
            model_name='t_sistema',
            name='servicos',
            field=models.ManyToManyField(to='systems.t_Sistema_Servico', verbose_name='Serviço'),
        ),
        migrations.DeleteModel(
            name='t_Impacto_Dependencias',
        ),
        migrations.DeleteModel(
            name='t_Impacto_Fronteiras',
        ),
        migrations.DeleteModel(
            name='t_Impacto_Potenciais',
        ),
        migrations.AddField(
            model_name='t_impacto',
            name='dependencias',
            field=models.ManyToManyField(to='systems.t_Impacto_Dependencia', verbose_name='Dependências'),
        ),
        migrations.AddField(
            model_name='t_impacto',
            name='fronteiras',
            field=models.ManyToManyField(to='systems.t_Impacto_Fronteira', verbose_name='Fronteiras'),
        ),
        migrations.AddField(
            model_name='t_impacto',
            name='impactos_Potenciais',
            field=models.ManyToManyField(to='systems.t_Impacto_Potencial', verbose_name='Impactos Potenciais'),
        ),
    ]
