# Generated by Django 2.2.3 on 2019-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20191210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sistema',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
