# Generated by Django 2.2.3 on 2019-10-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20191012_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_area_desenvolvimento',
            name='area_Dev',
            field=models.CharField(max_length=128, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='t_area_desenvolvimento',
            name='coordenador_Area_Dev',
            field=models.CharField(blank=True, max_length=128, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='t_area_desenvolvimento',
            name='gerente_Area_Dev',
            field=models.CharField(blank=True, max_length=128, verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='t_area_suporte',
            name='area_Sup',
            field=models.CharField(max_length=128, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='t_area_suporte',
            name='coordenador_Area_Sup',
            field=models.CharField(blank=True, max_length=128, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='t_area_suporte',
            name='gerente_Area_Sup',
            field=models.CharField(blank=True, max_length=128, verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='t_responsavel_desenvolvimento',
            name='fk_Area_Dev',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.t_Area_Desenvolvimento', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='t_responsavel_suporte',
            name='fk_Area_Sup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.t_Area_Suporte', verbose_name='Área'),
        ),
    ]
