# Generated by Django 2.2.3 on 2019-12-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20191219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_infraestrutura',
            name='camada_aplicacao',
            field=models.CharField(max_length=255, verbose_name='Descreva brevemente a estrutura da camada da aplicação:'),
        ),
        migrations.AlterField(
            model_name='t_infraestrutura',
            name='camada_balanceador',
            field=models.CharField(max_length=255, verbose_name='Descreva brevemente a estrutura da camada do balanceador:'),
        ),
        migrations.AlterField(
            model_name='t_infraestrutura',
            name='camada_banco_dados',
            field=models.CharField(max_length=255, verbose_name='Descreva brevemente a estrutura da camada do banco de dados:'),
        ),
        migrations.AlterField(
            model_name='t_infraestrutura',
            name='impacto_Direto',
            field=models.ManyToManyField(blank=True, help_text="Mantenha pressionado o 'Control', ou 'Command' no Mac, para selecionar mais de uma opção.", to='systems.t_Impacto_Direto', verbose_name='Impacto(s) Direto(s):'),
        ),
        migrations.AlterField(
            model_name='t_infraestrutura',
            name='impacto_Indireto',
            field=models.ManyToManyField(blank=True, help_text="Mantenha pressionado o 'Control', ou 'Command' no Mac, para selecionar mais de uma opção.", to='systems.t_Impacto_Indireto', verbose_name='Impacto(s) Indireto(s):'),
        ),
        migrations.AlterField(
            model_name='t_sistema',
            name='fk_Cadeia_Servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.t_Cadeia_Servico', verbose_name='Cadeia de Serviço:'),
        ),
        migrations.AlterField(
            model_name='t_sistema',
            name='fk_Responsavel_Dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.t_Responsavel_Desenvolvimento', verbose_name='Responsável pelo Desenvolvimento:'),
        ),
        migrations.AlterField(
            model_name='t_sistema',
            name='fk_Responsavel_Sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.t_Responsavel_Suporte', verbose_name='Responsável pelo Suporte:'),
        ),
        migrations.AlterField(
            model_name='t_sistema',
            name='sistema',
            field=models.CharField(max_length=128, verbose_name='Nome da Aplicação:'),
        ),
    ]
