# Generated by Django 2.2.3 on 2019-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20191111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='url_Ficheiro',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL - Documentação'),
        ),
    ]
