# Generated by Django 2.2.3 on 2019-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20191219_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sistema',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição do(s) Serviço(s):'),
        ),
    ]
