# Generated by Django 2.2.3 on 2019-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20191012_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_cadeia_servico',
            name='cadeia_Servico',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
