# Generated by Django 2.2.3 on 2019-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20191111_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='camada_aplicacao',
            field=models.CharField(choices=[('Disponibilidade', (('', ''), ('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A'))), ('Contingência', (('', ''), ('Contingência Local Manual', 'Contingência Local Manual'), ('Contingência Local Automática', 'Contingência Local Automática'), ('Contingência Entre Sites Manual', 'Contingência Entre Sites Manual'), ('Contingência Entre Sites Automática', 'Contingência Entre Sites Automática'), ('N/A', 'N/A')))], default='', max_length=35, verbose_name='Camada da Aplicação'),
        ),
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='camada_balanceador',
            field=models.CharField(choices=[('Disponibilidade', (('', ''), ('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A'))), ('Contingência', (('', ''), ('Contingência Local Manual', 'Contingência Local Manual'), ('Contingência Local Automática', 'Contingência Local Automática'), ('Contingência Entre Sites Manual', 'Contingência Entre Sites Manual'), ('Contingência Entre Sites Automática', 'Contingência Entre Sites Automática'), ('N/A', 'N/A')))], default='', max_length=35, verbose_name='Camada do Balanceador'),
        ),
        migrations.AlterField(
            model_name='t_continuidade_tecnologica',
            name='camada_banco_dados',
            field=models.CharField(choices=[('Disponibilidade', (('', ''), ('Alta Disp. Local', 'Alta Disp. Local'), ('Alta Disp. Entre Sites', 'Alta Disp. Entre Sites'), ('Infraestrutura Segmentada Por Raias', 'Infraestrutura Segmentada Por Raias'), ('N/A', 'N/A'))), ('Contingência', (('', ''), ('Contingência Local Manual', 'Contingência Local Manual'), ('Contingência Local Automática', 'Contingência Local Automática'), ('Contingência Entre Sites Manual', 'Contingência Entre Sites Manual'), ('Contingência Entre Sites Automática', 'Contingência Entre Sites Automática'), ('N/A', 'N/A')))], default='', max_length=35, verbose_name='Camada do Banco de Dados'),
        ),
    ]
