# Generated by Django 2.2.3 on 2019-10-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_auto_20191012_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_responsavel_desenvolvimento',
            options={'verbose_name': 'Responsável pelo Desenvolvimento', 'verbose_name_plural': 'Responsável pelo Desenvolvimento'},
        ),
    ]
