# Generated by Django 2.2.3 on 2019-10-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20191012_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_responsavel_desenvolvimento',
            options={'verbose_name': 'Responsável pelo Desenvolvimento', 'verbose_name_plural': 'Responsáveis pelo Desenvolvimento'},
        ),
        migrations.AlterModelOptions(
            name='t_responsavel_suporte',
            options={'verbose_name': 'Responsável pelo Suporte', 'verbose_name_plural': 'Responsáveis Suporte'},
        ),
    ]
