# Generated by Django 2.2.3 on 2019-10-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_auto_20191012_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_area_desenvolvimento',
            options={'verbose_name': 'Área de Desenvolvimento', 'verbose_name_plural': 'Áreas de Desenvolvimento'},
        ),
        migrations.AlterModelOptions(
            name='t_area_suporte',
            options={'verbose_name': 'Área de Suporte', 'verbose_name_plural': 'Áreas de Suporte'},
        ),
    ]
