# Generated by Django 2.2.3 on 2019-10-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_auto_20191012_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_responsavel_suporte',
            options={'verbose_name': 'Responsável pelo Suporte', 'verbose_name_plural': 'Responsáveis pelo Suporte'},
        ),
    ]
