# Generated by Django 2.2.3 on 2019-10-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_auto_20191012_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_Criticidade_Suporte',
            new_name='t_Criticidade',
        ),
    ]
