# Generated by Django 2.2.3 on 2019-10-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_auto_20191012_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_criticidade',
            options={'verbose_name': 'Nível de Criticidade', 'verbose_name_plural': 'Nível de Criticidade'},
        ),
    ]
