# Generated by Django 2.2.3 on 2019-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_auto_20191012_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_sistema_janelas',
            options={'verbose_name': 'Sistema (Janela Crítica)', 'verbose_name_plural': 'Sistemas (Janelas Críticas)'},
        ),
        migrations.AlterModelOptions(
            name='t_sistema_servico',
            options={'verbose_name': 'Sistema (Serviço)', 'verbose_name_plural': 'Sistemas (Serviços)'},
        ),
        migrations.AlterField(
            model_name='t_sistema_janelas',
            name='janela_Critica',
            field=models.CharField(max_length=128, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='t_sistema_servico',
            name='servico',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
    ]
