# Generated by Django 2.2.3 on 2019-10-13 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20191012_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_contingencia_arquitetura_nome',
            options={'verbose_name': 'Contingência (Arquitetura TecBan)', 'verbose_name_plural': 'Contingências (Arquitetura TecBan)'},
        ),
        migrations.AlterField(
            model_name='t_contingencia_arquitetura_nome',
            name='fk_Contingencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.t_Contingencia', verbose_name='Sistema Contingenciado'),
        ),
        migrations.AlterField(
            model_name='t_contingencia_arquitetura_nome',
            name='nome_Contingencia',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
