# Generated by Django 2.2.3 on 2019-10-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_auto_20191013_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contingencia_arquitetura_nome',
            name='nome_Contingencia',
            field=models.CharField(max_length=128, verbose_name='Nome da Contingência'),
        ),
        migrations.AlterField(
            model_name='t_contingencia_usuario_nome',
            name='fk_Contingencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.t_Contingencia', verbose_name='Sistema Contingenciado'),
        ),
        migrations.AlterField(
            model_name='t_contingencia_usuario_nome',
            name='nome_Contingencia',
            field=models.CharField(max_length=128, verbose_name='Nome da Contingência'),
        ),
    ]
