# Generated by Django 2.2.3 on 2019-10-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_auto_20191013_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_contingencia_usuario_nome',
            options={'verbose_name': 'Contingência (Usuário)', 'verbose_name_plural': 'Contingências (Usuário)'},
        ),
        migrations.AlterModelOptions(
            name='t_continuidade_tecnologica_sites',
            options={'verbose_name': 'Continuidade Tecnológica (Site)', 'verbose_name_plural': 'Continuidade Tecnológica (Sites)'},
        ),
        migrations.AlterField(
            model_name='t_continuidade_tecnologica_sites',
            name='fk_Continuidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='systems.t_Continuidade_Tecnologica', verbose_name='Continuidade Tecnológica'),
        ),
    ]
