# Generated by Django 2.2.3 on 2019-10-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_auto_20191013_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_impacto_dependencia',
            options={'verbose_name': 'Impacto (Dependência)', 'verbose_name_plural': 'Impactos (Dependências)'},
        ),
        migrations.AlterModelOptions(
            name='t_impacto_fronteira',
            options={'verbose_name': 'Impacto (Fronteira)', 'verbose_name_plural': 'Impactos (Fronteiras)'},
        ),
        migrations.AlterField(
            model_name='t_impacto_dependencia',
            name='dependencia',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='t_impacto_fronteira',
            name='fronteira',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='t_impacto_potencial',
            name='impacto_Potencial',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
