# Generated by Django 2.2.3 on 2019-10-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0018_auto_20191013_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_impacto_dependencia',
            name='dependencia',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nome da Aplicação Dependente'),
        ),
        migrations.AlterField(
            model_name='t_impacto_fronteira',
            name='fronteira',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nome da Aplicação Que Faz Fronteira'),
        ),
        migrations.AlterField(
            model_name='t_impacto_potencial',
            name='impacto_Potencial',
            field=models.CharField(max_length=255, verbose_name='Consequência Durante Indisponibilidade'),
        ),
    ]
