# Generated by Django 2.2.3 on 2019-10-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0020_auto_20191013_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_Impacto_Usuario',
            fields=[
                ('cod_Usuario_Chave', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_Chave', models.CharField(max_length=128, verbose_name='Usuário(s) Chave(s)')),
            ],
            options={
                'verbose_name': 'Impacto - Usuário Chave',
                'verbose_name_plural': 'Impacto - Usuários Chave',
            },
        ),
        migrations.DeleteModel(
            name='t_Impacto_Usuarios',
        ),
        migrations.AddField(
            model_name='t_impacto',
            name='usuario_Chave',
            field=models.ManyToManyField(to='systems.t_Impacto_Usuario', verbose_name='Usuário Chave'),
        ),
    ]
