# Generated by Django 2.2.3 on 2019-10-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0021_auto_20191013_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_impacto_usuario',
            options={'verbose_name': 'Impacto (Usuário Chave)', 'verbose_name_plural': 'Impactos (Usuários Chave)'},
        ),
        migrations.AlterField(
            model_name='t_impacto_usuario',
            name='usuario_Chave',
            field=models.CharField(max_length=128, verbose_name='Usuário Chave'),
        ),
    ]
