# Generated by Django 2.2.3 on 2019-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0022_auto_20191013_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_impacto',
            name='usuario_Chave',
            field=models.ManyToManyField(to='systems.t_Impacto_Usuario', verbose_name='Usuários Chave'),
        ),
    ]
