# Generated by Django 2.2.3 on 2019-10-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0023_auto_20191013_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_Contingencia_Arquitetura_Nome',
            new_name='t_Contingencia_Arquitetura',
        ),
        migrations.RenameModel(
            old_name='t_Contingencia_Usuario_Nome',
            new_name='t_Contingencia_Usuario',
        ),
    ]
